apiVersion: v1
kind: Service
metadata:
  name: survey-app
  namespace: python-app
  labels:
    app: survey-app
spec:
  selector:
    app: survey-app
  type: LoadBalancer
  ports:
  - port: 8000 
    targetPort: 8000