version: "3.8"
services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "4000:8000"
    volumes:
      - .:/usr/src/app
      - sqlite_data:/usr/src/app/db
    environment:
      - DATABASE_URL=sqlite:////usr/src/app/db/data.sqlite3

volumes:
  sqlite_data:
